### ISSUE TITLE
Column names get camel cased

### ISSUE THREAD

**Issue by anton-johansson** [speedment/speedment#102]
Column names seem to get camel cased when becoming properties in the Speedment-generated objects. **This is probably a good idea**. However, I have some column names that include acronyms, such as ```profileURL```. I would like this property to still be called ```profileURL```, ```getProfileURL()```, etc. Would that be possible, somehow?

**Comment by Pyknic** [comment]
Yes, the reason for this is that our chosen code standard indicate that acronyms should be written "getUrl" instead of "getURL", but I agree with you that the user should be able to configure their own code standard for the generated code. This is not possible right now due to the fact that we currently name variables, methods and classes using static functions, but if we refactored those functions into a component, it would be configurable by the user.

**Comment by anton-johansson** [comment]
Sounds good!

**Comment by Pyknic** [comment]
This is now fixed!
