### ISSUE TITLE
PostgreSQL boolean column is mapped to int

### ISSUE THREAD

**Issue by robertsv** [speedment/speedment#127]
Bug description: Speedment generates `int` typed attribute for a `boolean` column
DB: PostgreSQL 9.3
Speedment version: 2.2.3

**Comment by minborg** [comment]
Thanks for the head up! Would it be possible to add a comment how your table definition looks like? Are you using BIT(n)?

**Comment by robertsv** [comment]
@minborg 

> Would it be possible to add a comment how your table definition looks like?

```sql
CREATE TABLE scheduled_job
(
  id bigint NOT NULL,
  path character varying(512) NOT NULL,
  schedule character varying(255) NOT NULL,
  status character varying(512) NOT NULL,
  enabled boolean NOT NULL
)
```

> Are you using BIT(n)?

What is it?

**Comment by Pyknic** [comment]
What @minborg asked was if the data type of the column was "BIT", but in your supplied structure we can see that it is actually a boolean. I have changed status of this to bug since it should clearly map booleans to booleans. 

If you want a (somewhat) quick fix, you could try creating a custom TypeMapper and use it to map Integers to Booleans. Such a type mapper could be useful even in other cases after we fix this bug so if you want to commit it to the project I would definitly accept it!

**Comment by Pyknic** [comment]
I have created a separate issue #138 for creating the TypeMapper from Integer to Boolean since it is not a fix for this bug, just a workaround. Feel free to grab it if you have time!

**Comment by robertsv** [comment]
@Pyknic - Can you assign this issue on me, so that I can start work on it!

**Comment by Pyknic** [comment]
Hi @robertsv! How is it going with the issue?

**Comment by minborg** [comment]
FIxed in new type mapper
