### ISSUE TITLE
Support for schema-free / mixed-schema databases

### ISSUE THREAD

**Issue by fabriziofortino** [speedment/speedment#174]
I was considering to create a new database extension for speedment to work with OrientDB (http://orientdb.com/). OrientDB supports schema-free and mixed-schema modes (http://orientdb.com/docs/2.1/Schema.html). This allows the developer to be strict on some fields and "relaxed" on others. I have seen the mongodb connector and it creates the schema for each collection/table using the first document in each collection (https://github.com/Pyknic/speedment-mongodb-connector/blob/master/src/main/java/com/speedment/connector/mongodb/MongoDbmsHandler.java#L160). Fields that don't appear in the first documents cannot be handled. This could be a problem in my OrientDB extension.

It would be nice to add a new method to the speedment Entity interface (http://static.javadoc.io/com.speedment/speedment/2.3.1/com/speedment/Entity.html) to return the raw record. Something like:

```java
public Map<String, Object> raw() // or getRaw / getRawRecord
```

With an additional method like this speedment could be very useful for schema-free or mixed-schema databases. WDYT?

**Comment by Pyknic** [comment]
Hi! OrientDB looks cool! My MongoDB connector was sadly never completed since the SQL language was a bit too tighly coupled into Speedment, but it is nice to see that it can serve some other purpose.

As to the raw request, it is possible to create that kind of method without effecting the Entity API. The manager calready contains methods for getting a stream of the fields that an entity has as (`fields()`) well as a method for retrieving the value of a field (`get()`).

Here is an example of this:
```java
public final class RawEntityUtil {

    public static <ENTITY> Map<String, Object> 
    getRawFrom(ENTITY, Manager<ENTITY> manager) {
        return MapStream.fromKeys(manager.fields(), FieldTrait::getIdentifier)
            .mapValue(fi -> manager.get(entity, (FieldIdentifier<ENTITY>) fi))
            .mapKey(ft -> ft.findColumn(speedment()))
            .filterKey(Optional::isPresent)
            .mapKey(Optional::get)
            .mapKey(Column::getName)
            .toMap();
    }

    private RawEntityUtil() {}
}
```

If it is performance critical, I would suggest not converting it into a map at all but instead keep the manager and read it directly using the `get()`-method.

**Comment by fabriziofortino** [comment]
Thank you for the explanation. I'll try to create an OrientDB extension in the next weeks. I'll let you know how it goes.
