### ISSUE TITLE
Use Java 8 Instant for time mapping

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#181]

**Comment by Pyknic** [comment]
We should support mapping to both Instant and LocalDate/LocalDateTime. This might be a bit complicated since the mapper must be able to handle the case when the times of the database is zone-specific and the java world is zone-less. One way of supporting this could be to store the database timezone as a member in the TypeMapper class and use it when converting back to the database.

**Comment by minborg** [comment]
Proposed mappings at the end of the article http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html
