### ISSUE TITLE
Support tablename prefixes

### ISSUE THREAD

**Issue by Timmeey** [speedment/speedment#205]
If speedment is generated against a database which has 2 tables. Let's say Device and User. Make it possible that on instantiation (at runtime) speedment accepts a prefix for those tables. 
`new SpeedmentApplication().withPrefix("test_").build()` which would then use the the tables "test_Device" and "test_User", instead of "Device" and "User".

**Comment by anton-johansson** [comment]
I don't know your exact use case here, but I assume it is for some sort of automatic testing. If so, isn't it better to use a separate database with the same structure? Then you can use existing functionality, such as ```new SpeedmentApplication().withXxx("yyy").withSchema("TestDatabase");```.

**Comment by Timmeey** [comment]
Sure for Testing you would use a separate database.

I was more thinking about legacy code, or databases that were created by other software. Example
Owncloud (i know it is outdated, but just as ONE example) [OwncloudUsingTablesPrefixes](https://forum.owncloud.org/viewtopic.php?t=20984)

**Comment by Pyknic** [comment]
You can choose to point an manager to a different table by overriding the `getTable()`-method in the manager implementation class. In that way you can have legacy tables in the database that is not visible in the generated code.

For an example, I have a database with two tables, `physician` and `test_physician`. I don't want to generate duplicate entities so I disable the `test_physician` table in the Speedment UI. If I want to point the generated `PhysicianManager` to use the test table instead, I can simply open the generated `PhysicianManagerImpl`-class and add the following:

```java
public final class PhysicianManagerImpl extends GeneratedPhysicianManagerImpl implements PhysicianManager {
    
    public PhysicianManagerImpl(Speedment speedment) {
        super(speedment);
    }
    
    // Add the following:
    @Override
    public Table getTable() {
        return speedment().get(ProjectComponent.class)
            .getProject()
            .findTableByName("db0.physicians.test_physician"); // <-- The table is different
    }
}
```

Speedment will now load entities from the test table instead of the real one. Use this with caution though, if the tables are structurally different you might get unspecified behaviour.
