### ISSUE TITLE
Optimize Predicate::or SQL rendering

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#389]
Currently we optimize predicates that are composed using the `Predicate::and` method but not predicates that are composed using the `Predicate::or` function. This can result in poor performance for certain kind of streams. Here is one example:

``` java
        Predicate<Hare> isAdult = Hare.AGE.greaterThan(2);
        Predicate<Hare> nameContains_e = Hare.NAME.contains("e");

        Predicate<Hare> isAdultOrNameContains_e = isAdult.or(nameContains_e);

        hares.stream()
            .filter(isAdultOrNameContains_e)
            .forEachOrdered(System.out::println);
```
which will result in all rows being pulled in to the JVM.

Support could be implemented stepwise starting with the simple case where there are only `or` predicates and then later the more general case where there are several predicates composed with either the `and` or the `'or`method and with several `filter` operations in the stream pipeline.

Affects documentation.

**Comment by minborg** [comment]
This is a duplicate of #195

**Comment by paxbit** [comment]
We just hit the same issue and I can see there are already two bugs recorded for it. This one and #195.

However, reading both issues takes a bit of my confidence in Speedment away. Here's why:
* #195 is open for a whole year.
* both issues are flagged as "enhancement"

To me this suggests a questionable line of thinking. I think this is clearly a bug, definitely not an enhancement. Having .and(...) generating proper WHERE constraints while .or(...) effectively filters in-memory is a problem as soon as you have more than a couple of rows in a table and I think it is in general violation of Speedments API contract. This should ideally have been covered by a test unit from day one - validating each an every logical predicate constellation actually renders matching SQL. It obviously wasn't. Which I think is fine if:
* it was acknowledged as an actual bug
* it gets fixed within weeks rather than years

At the very least, since this is known for a long time now, a warning could be generated if someone uses .or(...).

For any interested passerby, a somewhat crude workaround is documented here:
https://speedment.github.io/speedment-doc/predicate.html#or 
However this gets more and more inefficient as you link more and more OR constraints together. One statement per constraint is then generated. Also the .distinct() part is again done in-memory.

Guys? Are you still invested in the project?

**Comment by minborg** [comment]
Thanks for the input @paxbit. Prioritizing between issues is always hard and that is why it is so important with comments like yours. 

I recently re-classified this issue as a bug (though "enhancement" was not removed) and I agree that we should get this issue fixed. I have up-voted it accordingly and will consider it for coming releases. 

The idea to solve this is to implement an Expression tree where .and() and .or() can be combined in any order and depth. The tree can then be rendered to pure SQL.

I will open a new issue for the .distinct() part.

We are very committed to developing Speedment. Check out the releases and you will see that we have fixed a massive amount of issues (improvements and bugs) over the last years. Any help from the open-source community is greatly appreciated.

**Comment by minborg** [comment]
I've added a new tag "Community Request" which I tagged this issue with.
