### ISSUE TITLE
SpeedmentApplication.configure() is losing type information

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#457]
Currently when a manager is configured using the `SpeedmentApplication.configure()` the specific manager type is lost upon build.

This works: 

        Manager<Inventory> inventoriesWithStategy = app
            .configure(InventoryManager.class)
            .withParallelStrategy(ParallelStrategy.computeIntensityHigh())
            .build();

This does not work:

        InventoryManager inventoriesWithStategy = app
            .configure(InventoryManager.class)
            .withParallelStrategy(ParallelStrategy.computeIntensityHigh())
            .build();

As can be seen, we cannot regain the original Manager type `InventoryManager`

**Comment by Pyknic** [comment]
A problem with returning an `InventoryManager` is that there is no way of knowing how to construct that instance. The user might have added a non-default constructor since it is a class open for modifications.

One way to solve it would be to let `.configure` take a `Supplier<? extends Manager<? super ENTITY>>` instead of a class. The type could then be carried by the builder as a generic variable.

Example:
```java
InventoryManager inventoriesWithStategy = app
    .configure(InventoryManagerImpl::new)
    .withParallelStrategy(ParallelStrategy.computeIntensityHigh())
    .build();
```

If you have changed the constructor, you are responsible for creating the supplier yourself.

**Comment by minborg** [comment]
We should have a more general way of streaming (see #159) where `mgr.stream()` takes a parameter `StreamConfiguration` for parallel strategy, object reuse, immutablility etc.
