### ISSUE TITLE
Code generation does not support Date fields

### ISSUE THREAD

**Issue by atasc** [speedment/speedment#50]
Hi,
I'm trying to generate code from a MySQL DB but I get the following exception:

2015-10-21T18:10:54.625Z ERROR [JavaFX Application Thread] (c.s.i.g.c.SceneController) - Error! Failed to generate code.
java.lang.NullPointerException: The JavaTypeMapperComponent does not have a mapping for com.speedment.internal.core.config.dbms.MySqlDbmsType@76f9e4f0, java.util.Date
......

It seems caused by a field of type Date

**Comment by Pyknic** [comment]
This is fixed in the development branch and will be available in the 2.2.0 release. We accidentally imported java.util.Date instead of java.sql.Date. Hopefully we will get the new release out in a few days from now. If you want you can check out the 2.1.3-SNAPSHOT version and build it yourself in the meantime.

**Comment by Pyknic** [comment]
This is the same as #42.
