### ISSUE TITLE
The PostgressDB with JSONB colums is throwing errors in generate phase

### ISSUE THREAD

**Issue by srinivasanraghavan** [speedment/speedment#530]
Connected the mvn speedment:tool and  tolls is throwing the  following 
![bug](https://user-images.githubusercontent.com/4154181/31813433-e630c864-b5b8-11e7-9ff2-f97e1e5381ea.png)

**Comment by Pyknic** [comment]
Hi! The tool is showing warnings like this because it finds columns that it doesn't know how to map. I agree that this is a bit irritating since the messages cover the entire screen. The problem however is easily fixed. Speedment maps columns it doesn't recognize to `Object`, but they can be cast to the appropriate type when the entity is constructed. To do this automatically, you can create your own `TypeMapper` that maps from `Object` to `String` by casting and then select it in the tool. Instructions on how to add a custom type mapper [can be found here](https://speedment.github.io/speedment-doc/maven.html#adding-a-type-mapper).

The long-term fix would be to fix the Speedment PostgreSQL Connector so that it recognizes `JSON` and `JSONB`-columns as `String`-types.

I have created two issues in response to this:
* Limit the number of warnings to show to one column (#531)
* Make PostgreSQL recognize JSON and JSONB types (#532)

You are very welcome to look at issue #532 if you are interested. It is not very hard to implement and a good thing to start with if you would like to contribute. :)
