### ISSUE TITLE
Sakila DB gives uncompilable code for PostgreSQL

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#546]
There are some FK that will be of different type (referencing and referenced columns are mapped to different types).

**Comment by lawesson** [comment]
The example database pagila v0.10.1, a Postgres port of the MySQL Sakila database, has several problems of the following type:

CREATE TABLE A (
  ...
  B_id smallint,
  ...
)

CREATE TABLE B (
   ...
  B_id integer,
  ...
)

where there is a foreign key constraint from A.B_id to B.B_id.

Speedment does not support mismatching types in this case. The database can be fixed by replacing all instances of "_id smallint" with "_id integer", then Speedment will create code that compiles.
