### ISSUE TITLE
Document Speedment::close instead of Speedment:stop

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#608]
3.1 is using `.close()` instead of `.stop()'. Update manual, wiki, examples etc.

**Comment by minborg** [comment]
Also check `HasLogglerName` vs. `HasLoggerName`

**Comment by minborg** [comment]
Is there any use of `ColumnIdentifier` or `TableIdentifier` where `getXName` has been changed to `getXId`

**Comment by julgus** [comment]
I'm on it. Although would appreciate some clarification on the two last comments. Is ´´´HasLoggerName´´´ the correct one to use? 
and all ´´´getXNames´´´should be updated to ´´´getXId´´´ where the method is called in association with ´´´ColumnIdentifier´´´or ´´´TabelIdentifier´´´?

**Comment by julgus** [comment]
I have now changed `.stop()` to `.close()` in all documentation that I was able to find.

**Comment by minborg** [comment]
Previously, the class name `GetLoggler` was used instead of `GetLogger` (typo). I do not think we have that class in our documentation.
I do suspect that we have references to `TableIdentifier` and `ColumnIdentifier` though.

**Comment by julgus** [comment]
I found getXName in the following documents: 

**Tutorial: Social Network Guide**
getColumnName() -> getColumnId()

**Tutorial: Create an Event Sourced System** 
getTableName() -> getTableId()
getColumnName() -> getColumnId()

Although since updates are immediate and cannot be pushed to the development branch, these changes will have to be made later when a new version is released.
