### ISSUE TITLE
How to overwrite  log output use System.out.println 

### ISSUE THREAD

**Issue by xjr100419** [speedment/speedment#685]
when I set
`.withLogging(LogType.STREAM)`.

and the log messages out put use
`System.out.println `

How can I use the `org.slf4j.Logger` to  log the messages

**Comment by Pyknic** [comment]
Hi! To avoid creating a dependecy on Slf4j, Speedment uses its own logging system. However, it is possible to define a custom `LoggerFactory` to control where the logs are being outputted. Here I have [created a small adapter](https://gist.github.com/Pyknic/5983fbc8fd777738a510df34fdfcf1e6) that simply delegates all logs to Slf4j.

I might release it to the Maven Central Repository since it might be useful for more people.

**Comment by xjr100419** [comment]
ths
like orthers sayed  you are so handsome : )

**Comment by Pyknic** [comment]
Released it to maven central now so that it is easier to access. It should be live within an hour or so. You can see [the repository here](https://github.com/Pyknic/speedment-slf4j-adapter).
